---

- name: install enablerepo
  yum: name={{ item }} state=latest
  with_items:
    - epel-release

- name: pre insall redis
  yum: name={{ item }} state=latest
  with_items:
   - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  ignore_errors: True

- name: redis install
  yum: name=redis state=latest enablerepo=epel

- name: redis start
  service: name=redis state=started enabled=yes
