sudo: true
services:
  - docker

before_install:
  - docker pull ptpadan1246/amazonlinux_ansible
  - mkdir env
  - touch all_env.yml
  - echo 'mackerel_agent_apikey: ""' > env/all_env.yml

script:
  - docker build -f docker/Dockerfile-bot -t bot_docker .
  - docker build -f docker/Dockerfile-blog -t blog_docker .

notifications:
  slack:
    secure: CCKsufp9z/S+VEDKi6ZxqvnW5CC3RAWI+9S5KMtcQ/h+S4OegyyKBq1FXUvmHpx/4m3f/WUiZN5qWMiV3yQRL/gyw+thhApM9wVwIowGX7Lqs0q25vC7NbgpPJY2I2ifL8b88/ZUpuJbkRWOSyBBYRCUZaiiuRokBlU7DEIv1jl686T5k07m3vIPzXfrOCJHFUCT0Om2WdGRnSnKQGIYJe+pA97odGabEEXrHouhd8IUSLxztGhIlub1bYlEH3yU0cPf9hyZI9OROBX959VS2wior3WygKtfqllPpRdfy05JP0kOBa7CfqIvnV1AP8f3aJFGEX+H9Xz7lv+3oGxyMjz8b9EVNz+7UR5a5oHy6hShjnX0YX3aSd1MtISV441CNZN6r+NZR2uYWvqNusKc9MsQwDuQg5ER8hJMI2TCjj9bzUKX6IXUBRRyP46Ehw0jh7UExueQgc4VNVlk9EzpQ2PehGVVU1F90RFszTmixqrrYOX0vRq2Rec/oVFJtLzZu41FceAXH6p9ldXGriGoZdK6Kg8Icw1O/nHQZMNoNgJOvvUdgzQ6LjxNs06yz1wgO7Lofc6n7YhDFmtpL093Qty5Nm+E9z9k1Fn6GT15OXRFiBILBg7EApZFxgQEq1XBW1U/SNEQ3hYacRE5ujjTIEMMiEU+6iH82l+CPoFujBE=
