- hosts: blog_master
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - vars/blog/vars.yml
    - vars/blog/master.yml
    - env/all_env.yml
  roles:
    - setupcentos
    - ansible
    - YasushiKobayashi.apache
    - php7
    - composer
    - andrewrothstein.node-n
    - npm
    - mackerel.mackerel-agent

  tasks:
    - name: iptables stop
      service: name=iptables state=stopped enabled=off
