#!/usr/bin/env ansible-playbook -i hosts
- hosts: bot_vagrant
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - vars/bot/vars.yml
    - vars/bot/vagrant.yml
    - env/all_env.yml
  roles:
    - setupcentos
    - andrewrothstein.node-n
    - docker
    - npm
    - redis
    - mackerel.mackerel-agent
    - mackerel-plugin

  tasks:
    - name: yarn install
      become: no
      shell: yarn
      args:
        chdir: /home/vagrant/bot

    - name: yarn
      become: no
      shell: yarn
      args:
        chdir: /home/vagrant/bot/bot
