---
galaxy_info:
  author: Andrew Rothstein
  description: installs and configures git
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 24
    - name: Ubuntu
      versions:
        - xenial
    - name: GenericUnix
      versions:
        - all
        - any

  galaxy_tags:
    - development

dependencies: []
  
