---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
      - "{{ansible_distribution}}.yml"
      - "{{ansible_os_family}}.yml"
      skip: true

# tasks file for git
- name: install...
  package: name={{item}} state=present
  with_items:
    - git

- name: configurate git
  with_items: '{{git_config_protocol_map}}'
  blockinfile:
    create: yes
    dest: '{{git_target_cfg}}'
    mode: 0644
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item['uid']}}"
    block: |
      [url "{{item['url']}}"]
        insteadOf = {{item['insteadOf']}}
