FROM ptpadan1246/amazonlinux_ansible
MAINTAINER Yasushi Kobayashi <kobayashi@attela.jp>

WORKDIR /ansible
COPY ./ /ansible
RUN ansible-playbook -i test_hosts blog_master.yml --extra-vars 'env=docker'
