---
- name: import mackerel GPG key
  apt_key: url=https://mackerel.io/assets/files/GPG-KEY-mackerel state=present

- name: add repository 'mackerel'
  apt_repository: repo='deb http://apt.mackerel.io/debian/ mackerel contrib' state=present update_cache=yes

- name: install mackerel-agent
  apt:
    name: mackerel-agent
    state: latest
    update_cache: yes
    force: yes
    dpkg_options: 'force-confdef,force-confold'
  notify:
    - restart mackerel-agent

- name: install mackerel-agent-plugins
  apt: 
    name: mackerel-agent-plugins 
    state: latest
    update_cache: yes
    force: yes
    dpkg_options: 'force-confdef,force-confold'
  when: mackerel_use_plugins
  notify:
    - restart mackerel-agent
    
- name: install mackerel-check-plugins
  apt: 
    name: mackerel-check-plugins 
    state: latest
    update_cache: yes
    force: yes
    dpkg_options: 'force-confdef,force-confold'
  when: mackerel_use_plugins
  notify:
    - restart mackerel-agent
