---

- name: yum clean
  shell: yum clean all
  when: env != 'docker'

- name: upgrade all packages
  yum: name=* state=latest

- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - sqlite-devel
    - wget
    - expect
    - zip
    - unzip

- name: install jq
  get_url:
    url: http://stedolan.github.io/jq/download/linux64/jq
    dest: /usr/local/bin/
    mode: 0755

- name: ntp install
  yum: name={{ item }} state=latest
  with_items:
    - ntp

- name: ntp start
  service: name=ntpd state=started enabled=yes

- name: iptables stop
  service: name=iptables state=stopped enabled=off
  when: env != 'docker'
